### ISSUE TITLE
k8s's 0.14.0 rc break kube-register...

### ISSUE THREAD

**Issue by AntonioMeireles** [kelseyhightower/kube-register#13]
(or it's the other way around :smile: )

getting ...
```
Mar 30 18:35:38 master kube-register[1444]: error health checking 172.17.8.103: Get http://172.17.8.103:10250/healthz: dial tcp 172.17.8.103:10250: connection refused
Mar 30 18:35:38 master kube-register[1444]: error health checking 172.17.8.102: Get http://172.17.8.102:10250/healthz: dial tcp 172.17.8.102:10250: connection refused
Mar 30 18:36:08 master kube-register[1444]: Response: &http.Response{Status:"422 status code 422", StatusCode:422, Proto:"HTTP/1.1", ProtoMajor:1, ProtoMinor:1, Header:http.Header{"Content-Type":[]string{"application/json"}, "Date":[]st
Mar 30 18:36:08 master kube-register[1444]: Response Body:
Mar 30 18:36:08 master kube-register[1444]: {
Mar 30 18:36:08 master kube-register[1444]: "kind": "Status",
Mar 30 18:36:08 master kube-register[1444]: "creationTimestamp": null,
Mar 30 18:36:08 master kube-register[1444]: "apiVersion": "v1beta1",
Mar 30 18:36:08 master kube-register[1444]: "status": "Failure",
Mar 30 18:36:08 master kube-register[1444]: "message": "Node \"172.17.8.103\" is invalid: [status.Capacity: required value, spec.ExternalID: required value]",
Mar 30 18:36:08 master kube-register[1444]: "reason": "Invalid",
Mar 30 18:36:08 master kube-register[1444]: "details": {
Mar 30 18:36:08 master kube-register[1444]: "id": "172.17.8.103",
Mar 30 18:36:08 master kube-register[1444]: "kind": "Node",
Mar 30 18:36:08 master kube-register[1444]: "causes": [
Mar 30 18:36:08 master kube-register[1444]: {
Mar 30 18:36:08 master kube-register[1444]: "reason": "FieldValueRequired",
Mar 30 18:36:08 master kube-register[1444]: "message": "status.Capacity: required value",
Mar 30 18:36:08 master kube-register[1444]: "field": "status.Capacity"
Mar 30 18:36:08 master kube-register[1444]: },
Mar 30 18:36:08 master kube-register[1444]: {
Mar 30 18:36:08 master kube-register[1444]: "reason": "FieldValueRequired",
Mar 30 18:36:08 master kube-register[1444]: "message": "spec.ExternalID: required value",
Mar 30 18:36:08 master kube-register[1444]: "field": "spec.ExternalID"
Mar 30 18:36:08 master kube-register[1444]: }
Mar 30 18:36:08 master kube-register[1444]: ]
Mar 30 18:36:08 master kube-register[1444]: },
Mar 30 18:36:08 master kube-register[1444]: "code": 422
Mar 30 18:36:08 master kube-register[1444]: }
Mar 30 18:36:08 master kube-register[1444]: error registering: 172.17.8.103
Mar 30 18:36:08 master kube-register[1444]: Response: &http.Response{Status:"422 status code 422", StatusCode:422, Proto:"HTTP/1.1", ProtoMajor:1, ProtoMinor:1, Header:http.Header{"Content-Type":[]string{"application/json"}, "Date":[]st
Mar 30 18:36:08 master kube-register[1444]: Response Body:
Mar 30 18:36:08 master kube-register[1444]: {
Mar 30 18:36:08 master kube-register[1444]: "kind": "Status",
Mar 30 18:36:08 master kube-register[1444]: "creationTimestamp": null,
Mar 30 18:36:08 master kube-register[1444]: "apiVersion": "v1beta1",
Mar 30 18:36:08 master kube-register[1444]: "status": "Failure",
Mar 30 18:36:08 master kube-register[1444]: "message": "Node \"172.17.8.102\" is invalid: [status.Capacity: required value, spec.ExternalID: required value]",
Mar 30 18:36:08 master kube-register[1444]: "reason": "Invalid",
Mar 30 18:36:08 master kube-register[1444]: "details": {
Mar 30 18:36:08 master kube-register[1444]: "id": "172.17.8.102",
Mar 30 18:36:08 master kube-register[1444]: "kind": "Node",
Mar 30 18:36:08 master kube-register[1444]: "causes": [
Mar 30 18:36:08 master kube-register[1444]: {
Mar 30 18:36:08 master kube-register[1444]: "reason": "FieldValueRequired",
Mar 30 18:36:08 master kube-register[1444]: "message": "status.Capacity: required value",
Mar 30 18:36:08 master kube-register[1444]: "field": "status.Capacity"
Mar 30 18:36:08 master kube-register[1444]: },
Mar 30 18:36:08 master kube-register[1444]: {
Mar 30 18:36:08 master kube-register[1444]: "reason": "FieldValueRequired",
Mar 30 18:36:08 master kube-register[1444]: "message": "spec.ExternalID: required value",
Mar 30 18:36:08 master kube-register[1444]: "field": "spec.ExternalID"
Mar 30 18:36:08 master kube-register[1444]: }
Mar 30 18:36:08 master kube-register[1444]: ]
Mar 30 18:36:08 master kube-register[1444]: },
Mar 30 18:36:08 master kube-register[1444]: "code": 422
Mar 30 18:36:08 master kube-register[1444]: }
```

**Comment by AntonioMeireles** [comment]
cc @pires...

**Comment by bgrant0607** [comment]
Sorry. That was a breaking API change to Kubernetes. It was announced here:
https://groups.google.com/forum/#!topic/kubernetes-dev/G1UnzOo7o6A

This was the PR:
https://github.com/GoogleCloudPlatform/kubernetes/pull/5929

The check:
https://github.com/GoogleCloudPlatform/kubernetes/blob/3354cffbf0307fd4c2702c7f6612919aeab52b86/pkg/api/validation/validation.go#L962

Unfortunately, this is inconsistent with the documentation (omitempty implies optional):
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/api/v1beta3/types.go#L1002

@rjnagal @ddysher: What in Kubernetes depended upon ExternalID?

**Comment by rjnagal** [comment]
Sorry for the breakage, @AntonioMeireles.

I think the original bug was that ExternalID was not updatable. It did not need ExternalID to be required. It isn't really used anywhere yet, but Dawn mentioned that it will be assumed required as going forward.
Note that the registration also reports failure due to missing cpu, mem in capacity, which were also made required.

Do we get an instance id and capacity from the fleet machine response?

**Comment by AntonioMeireles** [comment]
@rjnagal simple question. not so simple answer, in the sense that's not exactly my call :-).

right now all one needs is to have a node registered in fleet with in its' metadata the "role=minion" set.
afaict nothing prohibits inherently one from adding more metadata to fleet per node (straight in the cloud-config, or whatever).

the only thing that may need some tought is the specific form on how we want to render that additional info and manage it (from all ends - k8s/CoreOS, etc). And in that regard i'm not certainly the most qualified to postulate about that ...   (@polvi|@philips|@kelseyhightower) certainnly are :smile:

OTOH i think that and regardless of this specific kube-register issue which is mostly contained within CoreOS/fleet land it would also be desirable to have an high level grammar/default set of conventions about those in order to avoid (too) OS/platform specific dialects.

**Comment by AntonioMeireles** [comment]
humm... and per GoogleCloudPlatform/kubernetes#6212 looks breaking change will be reverted... [just posting here to get issues well cross-linked, otherwise a few days from now, once this lefts my L1 cache, i'll get lost)

**Comment by baldwinSPC** [comment]
Just got nailed by this one, too. I'm open to helping assist on this.

**Comment by rjnagal** [comment]
Working on a fix to remove the capacity checks and default external id to node name.

**Comment by rjnagal** [comment]
@AntonioMeireles Fixed in https://github.com/GoogleCloudPlatform/kubernetes/pull/6325. Can you verify?

**Comment by AntonioMeireles** [comment]
@rjnagal sure. Easter's breaking a bit my usual *workflow*, so at worst i'll get you feedback by early monday. 

&& thanxs!

**Comment by mkulke** [comment]
I put the patch onto v0.14.1 and kube-register seems to work.

**Comment by rjnagal** [comment]
Thanks for verifying @mkulke !

**Comment by rjnagal** [comment]
We are building 0.14.2 today that will include the fix.

**Comment by pires** [comment]
@rjnagal great!

**Comment by AntonioMeireles** [comment]
@rjnagal thanxs! 

will close this once 0.14.2 hits the wires.

**Comment by AntonioMeireles** [comment]
closing, as 0.14.2 is already shipping and working again (regarding this) flawlessly.
