### ISSUE TITLE
Version kube-register

### ISSUE THREAD

**Issue by pires** [kelseyhightower/kube-register#16]
Right now, without me building it manually, I have no way to guarantee I'm using a certain version of this software. Would be great if it could be versioned and each release made available publicly.

**Comment by AntonioMeireles** [comment]
https://github.com/kelseyhightower/kube-register/releases/tag/v0.0.2 ...

**Comment by pires** [comment]
@AntonioMeireles you're a PITA! I've seen the commit too :-p just waiting on some response from @kelseyhightower - the lack of it may even mean the current behavior is not finished.

**Comment by AntonioMeireles** [comment]
see his comments on https://github.com/GoogleCloudPlatform/kubernetes/issues/6851... things may evolve but ongoing approach looks ok, and is backward compatible, in the sense that new blob wouldn't break old setups. (on new ones you inly have to add one flag)

**Comment by pires** [comment]
I'm happy with current solution as well.

**Comment by kelseyhightower** [comment]
@pires Yeah, I added the version yesterday. Now that people are using this thing we need to make it more official.

**Comment by kelseyhightower** [comment]
At this point I consider the version stuff working and I'm also release official binary releases as well.

**Comment by pires** [comment]
@kelseyhightower awesome! thanks

**Comment by ae6rt** [comment]
You have probably heard this by now, but in the odd case you have not:  the Kubernetes devs at Google are interested in folding kube-register into the k8s distribution itself.  So it can be tested with the rest of the build artifacts.
