### ISSUE TITLE
Register only use v1beta3 API

### ISSUE THREAD

**Issue by gosharplite** [kelseyhightower/kube-register#23]
Bump to v1 API should be considered.
v0.19.3 kubectl shows below logs.
```
$ kubectl describe node 192.168.7.11
W0625 11:23:12.403673    3581 request.go:302] field selector: v1 - events - involvedObject.name - 192.168.7.11: need to check if this is versioned correctly.
W0625 11:23:12.404226    3581 request.go:302] field selector: v1 - events - involvedObject.namespace - : need to check if this is versioned correctly.
W0625 11:23:12.404584    3581 request.go:302] field selector: v1 - events - involvedObject.kind - Node: need to check if this is versioned correctly.
W0625 11:23:12.404932    3581 request.go:302] field selector: v1 - events - involvedObject.uid - 192.168.7.11: need to check if this is versioned correctly.
Name:			192.168.7.11
Labels:			kubernetes.io/hostname=192.168.7.11
...
```

**Comment by fcantournet** [comment]
correct me if I'm wrong but isn't kube-register made obsolete by the auto-registration flag of kubelet ?
i.e as of Kubernetes v0.18.0

And if it isn't shouldn't we try to port what functionality still reside here inside kubelet ? (like -reverse-lookup)
Self-registration of nodes doesn't seems that crazy.

**Comment by gosharplite** [comment]
You are correct. I miss it completely. The flag is --register-node.

**Comment by fcantournet** [comment]
Just to complement on this. We still use kube-register for the moment (on a CoreOS baremetal cluster)
I'm not sure --register-node works perfectly if you don't have a proper cloud provider in Kubernetes.
For the moment letting fleet discover the nodes and kube-register do the work is better.
I'll try to provide a fix for the v1 API this week end.

**Comment by gosharplite** [comment]
We use [pure OpenStack ](http://docs.openstack.org/kilo/install-guide/install/apt/content/) with CoreOS as VM OS. Fleet is used to deployed etcd cluster, Kubernetes modules, Docker Registry 2.0 and a static file server.
I have tried --register-node and it works fine. Unless there is an issue, kube-register is out for now.
