### ISSUE TITLE
kube-register error

### ISSUE THREAD

**Issue by jothep** [kelseyhightower/kube-register#8]
HELLO
when I installed a master node and a minion node with coreos ,I try to create a pod.
but on the master node,kube-register show these error:
'''
t5master ~ # systemctl status kube-register
?.kube-register.service - Kubernetes Registration Service
   Loaded: loaded (/etc/systemd/system/kube-register.service; static)
   Active: active (running) since Wed 2014-12-17 17:13:38 UTC; 6h left
     Docs: https://github.com/kelseyhightower/kube-register
  Process: 692 ExecStartPre=/usr/bin/chmod +x /opt/bin/kube-register (code=exited, status=0/SUCCESS)
  Process: 690 ExecStartPre=/usr/bin/wget -N -P /opt/bin http://172.21.0.70/master/kube-register (code=exited, status=0/SUCCESS)
 Main PID: 693 (kube-register)
   CGroup: /system.slice/kube-register.service
           ?..693 /opt/bin/kube-register --metadata=role=node --fleet-endpoint=unix:///var/run/fleet.sock --api-endpoint=http://127.0.0.1:8080

Dec 17 10:23:16 t5master kube-register[693]: {"kind":"Status","creationTimestamp":null,"selfLink":"/api/v1beta1/minions","apiVersion":"v1beta1","status":"Failure","message":"minion \"172...},"code":409}
Dec 17 10:23:16 t5master kube-register[693]: error registering: 172.21.0.51
Dec 17 10:23:46 t5master kube-register[693]: Response: &http.Response{Status:"409 Conflict", StatusCode:409, Proto:"HTTP/1.1", ProtoMajor:1, ProtoMinor:1, Header:http.Header{"Content-Type":[]string{"...
Dec 17 10:23:46 t5master kube-register[693]: Response Body:
Dec 17 10:23:46 t5master kube-register[693]: {"kind":"Status","creationTimestamp":null,"selfLink":"/api/v1beta1/minions","apiVersion":"v1beta1","status":"Failure","message":"minion \"172...},"code":409}
Dec 17 10:23:46 t5master kube-register[693]: error registering: 172.21.0.51
Dec 17 10:24:16 t5master kube-register[693]: Response: &http.Response{Status:"409 Conflict", StatusCode:409, Proto:"HTTP/1.1", ProtoMajor:1, ProtoMinor:1, Header:http.Header{"Content-Type":[]string{"...
Dec 17 10:24:16 t5master kube-register[693]: Response Body:
Dec 17 10:24:16 t5master kube-register[693]: {"kind":"Status","creationTimestamp":null,"selfLink":"/api/v1beta1/minions","apiVersion":"v1beta1","status":"Failure","message":"minion \"172...},"code":409}
Dec 17 10:24:16 t5master kube-register[693]: error registering: 172.21.0.51
'''
on the minion node,kube-kubelete.service like this
'''

[Unit]
Description=Kubernetes Kubelet
Documentation=https://github.com/GoogleCloudPlatform/kubernetes
Requires=setup-network-environment.service
After=setup-network-environment.service
[Service]
EnvironmentFile=/etc/network-environment
ExecStartPre=/usr/bin/wget -N -P /opt/bin http://172.21.0.70/node/kubelet
ExecStartPre=/usr/bin/chmod +x /opt/bin/kubelet
ExecStart=/opt/bin/kubelet \
--address=0.0.0.0 \
--port=10250 \
--hostname_override=${DEFAULT_IPV4} \
--etcd_servers=http://172.21.0.50:4001 \
--logtostderr=true
Restart=always
RestartSec=10
'''

I had once change '--hostname_override=${DEFAULT_IPV4}' to '--hostname_override=172.21.0.51'
but after meet the error,I change it back to ${DEFAULT_IPV4}

'''
t5master ~ # journalctl -xn
-- Logs begin at Wed 2014-12-17 17:13:31 UTC, end at Wed 2014-12-17 10:34:16 UTC. --
Dec 17 10:33:46 t5master kube-register[693]: Response: &http.Response{Status:"409 Conflict", StatusCode:409, Proto:"HTTP/1.1", ProtoMajor:1, ProtoMinor:1, Header:http.Header{"Content-Type":[]string{"app
Dec 17 10:33:46 t5master systemd[1]: Starting Generate /run/coreos/motd...
-- Subject: Unit motdgen.service has begun with start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit motdgen.service has begun starting up.
Dec 17 10:33:46 t5master kube-register[693]: Response Body:
Dec 17 10:33:46 t5master kube-register[693]: {"kind":"Status","creationTimestamp":null,"selfLink":"/api/v1beta1/minions","apiVersion":"v1beta1","status":"Failure","message":"minion \"172.21.0.51\" alrea
Dec 17 10:33:46 t5master kube-register[693]: error registering: 172.21.0.51
Dec 17 10:33:46 t5master systemd[1]: Started Generate /run/coreos/motd.
-- Subject: Unit motdgen.service has finished start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit motdgen.service has finished starting up.
-- 
-- The start-up result is done.
Dec 17 10:34:16 t5master kube-register[693]: Response: &http.Response{Status:"409 Conflict", StatusCode:409, Proto:"HTTP/1.1", ProtoMajor:1, ProtoMinor:1, Header:http.Header{"Date":[]string{"Wed, 17 Dec
Dec 17 10:34:16 t5master kube-register[693]: Response Body:
Dec 17 10:34:16 t5master kube-register[693]: {"kind":"Status","creationTimestamp":null,"selfLink":"/api/v1beta1/minions","apiVersion":"v1beta1","status":"Failure","message":"minion \"172.21.0.51\" alrea
Dec 17 10:34:16 t5master kube-register[693]: error registering: 172.21.0.51
'''

I have no idea about it.PLS help me ,thanks.

**Comment by kelseyhightower** [comment]
This has been resolved for a while now, and kube-register has been updated to use v1beta3 api
